exclude: |
    (?x)(
      ^\.venv/|
      ^resources/|
      ^experiments/
    )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [ python ]
      - id: trailing-whitespace
        exclude_types: [ python ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff
        exclude: ^tests/
        args: [ --fix ]
      - id: ruff
        name: ruff-tests
        files: ^tests/
        args: [ --fix ]
      - id: ruff-format



  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 1.2.0.dev2
    hooks:
      - id: pyrefly-check
        name: pyrefly check
        language: system
        args: [
#          "--ignore=missing-import",
#          "--ignore=missing-source-for-stubs",
          "--project-excludes=tests",
          "--project-excludes=experiments",
          "--python-interpreter-path=.venv/bin/python"
        ]
